### ISSUE TITLE
My images aren't corresponding with the auto-fit 

### ISSUE THREAD

**Issue by Sophia-Villamayor** [Sophia-Villamayor/fancy-hover-boxes#1]
@mackenzierose

I followed the activity, but for some reason the images aren't scaling down to all fit together. Instead they're all overlapping one another. Any suggestions?
<img width="1680" alt="Screen Shot 2020-11-09 at 11 04 03 AM" src="https://user-images.githubusercontent.com/54897840/98565171-4c381e00-227b-11eb-95d3-6e408559c504.png">

**Comment by MacKenzieRose** [comment]
Hi~

This is because you haven't told the browser that you want to see 100% of your images (width-wise) at all times, in tandem with displaying as block elements. In previous assignments (possibly just from first year now), this is what the class of "img-flex" did for our code. 

If you adjust those two things, you should be good to go 😄

**Comment by Sophia-Villamayor** [comment]
@MacKenzieRose 
Thank you!! It didn't mention using image flex so I wasn't sure LOL 😂
